In [4]:
import pandas as pd
import numpy as np

In [5]:
user_features= pd.read_csv("C:/Users/manoj/Desktop/deep_learning/final_project/book/user_features_final.csv")
book_features = pd.read_csv("C:/Users/manoj/Desktop/deep_learning/final_project/book/books_with_latent_features.csv")
train_ratings = pd.read_csv("C:/Users/manoj/Desktop/deep_learning/final_project/book/train_ratings_set.csv")
test_ratings = pd.read_csv("C:/Users/manoj/Desktop/deep_learning/final_project/book/test_ratings_set.csv")

In [6]:
user_features.head()


user_id  avg_rating         0        1         2         3        4  \
0      6.0    4.285714  0.195982  0.01082  0.008561  0.007327  0.03029   
1   1006.0    3.784615  0.195982  0.01082  0.008561  0.007327  0.03029   
2   2006.0    4.100000  0.195982  0.01082  0.008561  0.007327  0.03029   
3   3006.0    3.819444  0.195982  0.01082  0.008561  0.007327  0.03029   
4   4006.0    3.317647  0.195982  0.01082  0.008561  0.007327  0.03029   

          5         6         7   ...           15   16        17        18  \
0  0.032636  0.028151  0.012982   ...     0.001723  0.0  0.011177  0.020266   
1  0.032636  0.028151  0.012982   ...     0.001723  0.0  0.011177  0.020266   
2  0.032636  0.028151  0.012982   ...     0.001723  0.0  0.011177  0.020266   
3  0.032636  0.028151  0.012982   ...     0.001723  0.0  0.011177  0.020266   
4  0.032636  0.028151  0.012982   ...     0.001723  0.0  0.011177  0.020266   

         19        20        21        22        23       24  
0  0.015214  0.020975  0.041102  0.010981  0.012653  0.06773  
1  0.015214  0.020975  0.041102  0.010981  0.012653  0.06773  
2  0.015214  0.020975  0.041102  0.010981  0.012653  0.06773  
3  0.015214  0.020975  0.041102  0.010981  0.012653  0.06773  
4  0.015214  0.020975  0.041102  0.010981  0.012653  0.06773  

[5 rows x 27 columns]

In [7]:
book_features.head()

book_id  books_count  original_publication_year  average_rating  \
0        1     1.151500                   0.170121        1.327789   
1        2     2.436243                   0.108104        1.720847   
2        3     0.881646                   0.153207       -1.698765   
3        4     2.412777                  -0.100498        0.974035   
4        5     7.510681                  -0.297825       -0.440977   

   ratings_count  work_ratings_count  work_text_reviews_count  ratings_1  \
0      30.036789           29.098997                24.874634   9.851855   
1      28.904534           28.250940                11.911526  11.176438   
2      24.229710           22.987143                15.037225  68.549476   
3      19.983656           19.554820                11.375772   8.904196   
4      16.710904           16.174804                 8.012977  12.793850   

   ratings_2  ratings_3    ...           15        16        17        18  \
0  12.846534  19.219327    ...     0.000000  0.000000  0.000000  0.000668   
1  10.143953  15.538545    ...     0.000000  0.000000  0.000000  0.000000   
2  44.633867  27.389823    ...     0.000000  0.000000  0.026678  0.000000   
3  11.763752  15.251665    ...     0.002680  0.000000  0.000000  0.009918   
4  20.018253  20.833128    ...     0.011253  0.000036  0.000000  0.000000   

        19   20   21        22        23        24  
0  0.00000  0.0  0.0  0.000000  0.009848  0.000000  
1  0.00000  0.0  0.0  0.000000  0.000000  0.000000  
2  0.00000  0.0  0.0  0.000000  0.007945  0.000000  
3  0.04148  0.0  0.0  0.000847  0.021077  0.031681  
4  0.00000  0.0  0.0  0.000000  0.000000  0.000000  

[5 rows x 37 columns]

In [8]:
train_ratings.head()

user_id  book_id  rating
0    36210      687       2
1        8     1509       1
2    42833     3128       4
3    39774       27       3
4    28108     1120       5

In [9]:
train_data = train_ratings.merge(user_features, how='left', on='user_id')

In [10]:
train_data.head()

user_id  book_id  rating  avg_rating         0         1         2  \
0   36210      687       2    3.536232  0.202367  0.033538  0.001456   
1       8     1509       1    3.421053  0.199233  0.013608  0.000536   
2   42833     3128       4    4.611940  0.196320  0.021527  0.007529   
3   39774       27       3    3.523810  0.156639  0.050961  0.051112   
4   28108     1120       5    4.678571  0.189999  0.032203  0.093174   

          3         4         5    ...           15        16        17  \
0  0.005575  0.006220  0.035502    ...     0.039848  0.022133  0.013898   
1  0.003621  0.023440  0.005159    ...     0.038217  0.034223  0.020021   
2  0.007994  0.014450  0.030204    ...     0.016280  0.000000  0.024576   
3  0.004160  0.012483  0.067711    ...     0.007462  0.015160  0.000000   
4  0.000000  0.000000  0.085931    ...     0.007475  0.020444  0.010343   

         18        19        20        21        22        23        24  
0  0.049059  0.012314  0.020619  0.007972  0.000000  0.002621  0.011240  
1  0.040144  0.000000  0.003788  0.006364  0.016232  0.000000  0.088559  
2  0.049903  0.033650  0.008952  0.010336  0.019030  0.012419  0.064434  
3  0.078406  0.000000  0.164855  0.007695  0.020140  0.013062  0.010286  
4  0.026707  0.000000  0.004009  0.019859  0.013946  0.007980  0.008841  

[5 rows x 29 columns]

In [11]:
train_data = train_data.merge(book_features, how="left", on='book_id')

In [12]:
train_data.head()

user_id  book_id  rating  avg_rating       0_x       1_x       2_x  \
0   36210      687       2    3.536232  0.202367  0.033538  0.001456   
1       8     1509       1    3.421053  0.199233  0.013608  0.000536   
2   42833     3128       4    4.611940  0.196320  0.021527  0.007529   
3   39774       27       3    3.523810  0.156639  0.050961  0.051112   
4   28108     1120       5    4.678571  0.189999  0.032203  0.093174   

        3_x       4_x       5_x    ...         15_y      16_y      17_y  18_y  \
0  0.005575  0.006220  0.035502    ...     0.001187  0.001917  0.000825   0.0   
1  0.003621  0.023440  0.005159    ...     0.000000  0.000000  0.000000   0.0   
2  0.007994  0.014450  0.030204    ...     0.000000  0.000000  0.000000   0.0   
3  0.004160  0.012483  0.067711    ...     0.000000  0.000000  0.008164   0.0   
4  0.000000  0.000000  0.085931    ...     0.001789  0.001892  0.000725   0.0   

       19_y      20_y      21_y      22_y      23_y      24_y  
0  0.002246  0.001787  0.003241  0.003036  0.004602  0.009414  
1  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
3  0.000000  0.003095  0.000000  0.015545  0.000000  0.029988  
4  0.003100  0.001592  0.004266  0.003174  0.004424  0.009140  

[5 rows x 65 columns]

In [13]:
train_data.shape


(4183180, 65)

In [14]:
test_data = test_ratings.merge(user_features,how= 'left', on='user_id')
test_data = test_data.merge(book_features,how='left',on='book_id')

In [15]:
test_data.head()

user_id  book_id  rating  avg_rating       0_x       1_x       2_x  \
0   18218      920       3    4.193548  0.182297  0.030095  0.013480   
1   34091      967       4    4.418605  0.202271  0.000826  0.013064   
2   41266       71       5    4.673077  0.199032  0.000000  0.012913   
3   47336      760       5    3.500000  0.176218  0.008017  0.035940   
4   20893      453       3    3.864198  0.197760  0.054557  0.007288   

        3_x       4_x       5_x    ...         15_y      16_y      17_y  \
0  0.015648  0.008251  0.024029    ...     0.000000  0.002823  0.000000   
1  0.000000  0.006972  0.042788    ...     0.000000  0.000000  0.000000   
2  0.022732  0.017535  0.062679    ...     0.000000  0.007510  0.000000   
3  0.016299  0.003869  0.043797    ...     0.000000  0.000000  0.000000   
4  0.025506  0.007168  0.056290    ...     0.000244  0.010929  0.000064   

       18_y      19_y      20_y      21_y      22_y      23_y      24_y  
0  0.000000  0.001451  0.010203  0.006101  0.001625  0.000187  0.000000  
1  0.000000  0.000000  0.000000  0.000000  0.729505  0.000000  0.000000  
2  0.000000  0.000000  0.018864  0.000000  0.000000  0.008654  0.007507  
3  0.000000  0.004526  0.000304  0.000000  0.001580  0.000362  0.000279  
4  0.000748  0.000000  0.000508  0.000511  0.004363  0.000302  0.018874  

[5 rows x 65 columns]

In [16]:
test_data.shape

(1792792, 65)

In [17]:
y_train= train_data.apply(lambda x:1 if x['rating']>3 else 0, axis=1)

In [18]:
x_columns = [c for c in train_data.columns if c not in ['user_id', 'book_id', 'rating']]


In [19]:
X_train = train_data[x_columns]

In [20]:
X_train.head()

avg_rating       0_x       1_x       2_x       3_x       4_x       5_x  \
0    3.536232  0.202367  0.033538  0.001456  0.005575  0.006220  0.035502   
1    3.421053  0.199233  0.013608  0.000536  0.003621  0.023440  0.005159   
2    4.611940  0.196320  0.021527  0.007529  0.007994  0.014450  0.030204   
3    3.523810  0.156639  0.050961  0.051112  0.004160  0.012483  0.067711   
4    4.678571  0.189999  0.032203  0.093174  0.000000  0.000000  0.085931   

        6_x       7_x       8_x    ...         15_y      16_y      17_y  18_y  \
0  0.000000  0.010712  0.029535    ...     0.001187  0.001917  0.000825   0.0   
1  0.022617  0.003733  0.000000    ...     0.000000  0.000000  0.000000   0.0   
2  0.021489  0.020012  0.009873    ...     0.000000  0.000000  0.000000   0.0   
3  0.017075  0.038733  0.056047    ...     0.000000  0.000000  0.008164   0.0   
4  0.003820  0.000925  0.005797    ...     0.001789  0.001892  0.000725   0.0   

       19_y      20_y      21_y      22_y      23_y      24_y  
0  0.002246  0.001787  0.003241  0.003036  0.004602  0.009414  
1  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
3  0.000000  0.003095  0.000000  0.015545  0.000000  0.029988  
4  0.003100  0.001592  0.004266  0.003174  0.004424  0.009140  

[5 rows x 62 columns]

# 1-5 Rating Prediction

In [21]:
from keras.utils import to_categorical
y_train_5 = train_data['rating']


Using TensorFlow backend.


In [22]:
train_data['rating'].value_counts(dropna=False)

4    1496995
5    1388429
3     959931
2     250846
1      86979
Name: rating, dtype: int64

In [23]:
y_train_5.shape

(4183180,)

In [24]:
X_train.shape

(4183180, 62)

# Logistic for Multiclass classification 

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [26]:
logreg_mul = LogisticRegression()

In [27]:
logreg_mul.fit(X_train,y_train_5)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [33]:

import pickle
filename = 'C:/Users/manoj/Desktop/deep_learning/final_project/book/logistic.h5'
pickle.dump(logreg_mul, open(filename, 'wb'))

In [34]:
y_test_5 = test_data['rating']

In [39]:
y_pred_mul = logreg_mul.predict(X_test)

In [40]:
logreg_mul.score(X_test,y_test_5)

0.469593237810075

In [41]:
probability_mul = logreg_mul.predict_proba(X_test)

In [42]:
probability_mul

array([[0.01156216, 0.04351422, 0.20242169, 0.37919129, 0.36331063],
       [0.00710289, 0.03133469, 0.17403922, 0.35402865, 0.43349456],
       [0.00417887, 0.01770923, 0.10020988, 0.28609682, 0.59180519],
       ...,
       [0.00709435, 0.02185633, 0.12503626, 0.33578721, 0.51022585],
       [0.00517214, 0.02783131, 0.19837452, 0.4242323 , 0.34438974],
       [0.05849375, 0.12867978, 0.37346506, 0.36215098, 0.07721042]])

In [46]:
class_1_prob=probability_mul[:,0]
class_2_prob=probability_mul[:,1]
class_3_prob=probability_mul[:,2]
class_4_prob=probability_mul[:,3]
class_5_prob=probability_mul[:,4]

In [147]:
from numpy import maximum

result_1 = maximum(class_1_prob,class_2_prob)
result_2 = maximum(result_1,class_3_prob)
result_3 = maximum(result_2,class_4_prob)
result_mul = maximum(result_3,class_5_prob)

In [170]:
y_pred_mul

array([4, 5, 5, ..., 5, 4, 3], dtype=int64)

In [43]:
evaluation_data = test_data[['user_id', 'book_id', 'rating']].copy()
evaluation_data['prediction']=y_pred_mul

In [44]:
evaluation_data['binary_rating']=y_test_5

In [47]:
evaluation_data['pred_proba']= class_5_prob

In [48]:


evaluation_data.head()

user_id  book_id  rating  prediction  binary_rating  pred_proba
0   18218      920       3           4              3    0.363311
1   34091      967       4           5              4    0.433495
2   41266       71       5           5              5    0.591805
3   47336      760       5           4              5    0.212271
4   20893      453       3           4              3    0.212236

In [51]:
cfm, p, r = replay_5star_results(evaluation_data)

In [52]:
cfm

array([[   117,     26,  15642,  15774,   5601],
       [   118,     23,  40041,  54725,  13462],
       [   122,     14,  91987, 243827,  74913],
       [    61,      3,  59203, 356146, 226443],
       [    37,      2,  17270, 183625, 393610]], dtype=int64)

In [53]:
print(p, r)

0.4519284456073333 0.469593237810075


In [54]:
aps, mAP, binary_mAP, binary_aps, skipped = top_n_5star_results(evaluation_data)

C:\Users\manoj\Anaconda3\lib\site-packages\sklearn\metrics\ranking.py:444: RuntimeWarning: invalid value encountered in true_divide
  recall = tps / tps[-1]


0 users evaluated
500 users evaluated
1000 users evaluated
1500 users evaluated
2000 users evaluated
2500 users evaluated
3000 users evaluated
3500 users evaluated
4000 users evaluated
4500 users evaluated
5000 users evaluated
5500 users evaluated
6000 users evaluated
6500 users evaluated
7000 users evaluated
7500 users evaluated
8000 users evaluated
8500 users evaluated
9000 users evaluated
9500 users evaluated
10000 users evaluated
10500 users evaluated
11000 users evaluated
11500 users evaluated
12000 users evaluated
12500 users evaluated
13000 users evaluated
13500 users evaluated
14000 users evaluated
14500 users evaluated
15000 users evaluated
15500 users evaluated
16000 users evaluated
16500 users evaluated
17000 users evaluated
17500 users evaluated
18000 users evaluated
18500 users evaluated
19000 users evaluated
19500 users evaluated
20000 users evaluated
20500 users evaluated
21000 users evaluated
21500 users evaluated
22000 users evaluated
22500 users evaluated
23000 users 

In [55]:
print(mAP, binary_mAP)

0.08672239114731486 0.6055031840278746


In [2]:
def top_n_5star_results(evaluation_data, n=10):
    """
    Evaluates the top 10 recommendations for each user.
    To be used for predictions for all books not in the user's training data.
    Parameter
    ---------
    evaluation_data: pd.DataFrame
        Expected columns: user_id, book_id, pred_proba, prediction, binary_rating
        pred_proba is the probability of being a 5
        prediction is the predicted class (1-5)
        rating is the original rating
    Returns
    -------
    The mAP and the number of users who had no historic rating data for any of their predicted top 10.
    Also calculates mAP for whether or not the user enjoyed the book (4 or 5).
    """
    users = list(set(evaluation_data['user_id'].tolist()))

    aps = []
    binary_aps = []
    not_scored = []
    counter = 0
    for u in users:
        results = evaluation_data[evaluation_data['user_id'] == u]
        books = results['book_id'].tolist()
        probs = np.asarray(results['pred_proba'])
        top_10 = np.argsort(probs)[:n]
        true = {1: [], 2: [], 3: [], 4: [], 5: []}
        pred = {1: [], 2: [], 3: [], 4: [], 5: []}
        top_binary_books = []
        top_binary_ratings = []
        matches = 0
        for i in top_10:
            rating = results[results['book_id'] == books[i]]['rating'].values
            
            if rating > 0:
                matches += 1
                p = int(results[results['book_id'] == books[i]]['prediction'].values)
                r = int(results[results['book_id'] == books[i]]['rating'].values)
                if p == r:
                    true[r].append(1)
                    pred[r].append(1)
                    for i in range(1, 6):
                        if i != r:
                            true[i].append(0)
                            pred[i].append(0)
                else:
                    true[r].append(1)
                    pred[r].append(0)
                    true[p].append(0)
                    pred[p].append(1)
                    for i in range(1, 6):
                        if i != r and i != p:
                            true[i].append(0)
                            pred[i].append(0)
                
                pb = 1 if p > 3 else 0
                rb = 1 if r > 3 else 0

                top_binary_books.append(pb)
                top_binary_ratings.append(rb)
                
        if matches > 0:
            ap_1 = average_precision_score(true[1], pred[1]) if len(true[1]) > 0 else 0
            ap_2 = average_precision_score(true[2], pred[2]) if len(true[2]) > 0 else 0
            ap_3 = average_precision_score(true[3], pred[3]) if len(true[3]) > 0 else 0
            ap_4 = average_precision_score(true[4], pred[4]) if len(true[4]) > 0 else 0
            ap_5 = average_precision_score(true[5], pred[5]) if len(true[5]) > 0 else 0
            weighted_ap = len(true[1])/matches * ap_1 + len(true[2])/matches * ap_2 + len(true[3])/matches * ap_3 + len(true[4])/matches * ap_4 + len(true[5])/matches * ap_5
            if np.isnan(weighted_ap):
                weighted_ap = 0
            aps.append(weighted_ap)
            
            b_ap = average_precision_score(top_binary_ratings, top_binary_books)
            if np.isnan(b_ap):
                b_ap = 0
            binary_aps.append(b_ap)
            
        else:
            not_scored.append(u)
        if counter % 500 == 0:
            print(str(counter), 'users evaluated')
        counter += 1

    mAP = np.asarray(aps).mean()
    binary_mAP = np.asarray(binary_aps).mean()
    return aps, mAP, binary_mAP, binary_aps, len(not_scored)

In [164]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test_5, y_pred_mul)


array([[   117,     26,  15642,  15774,   5601],
       [   118,     23,  40041,  54725,  13462],
       [   122,     14,  91987, 243827,  74913],
       [    61,      3,  59203, 356146, 226443],
       [    37,      2,  17270, 183625, 393610]], dtype=int64)

In [166]:
from sklearn import metrics
metrics.precision_score(y_test_5, y_pred_mul, average='macro')

0.39480199057643534

In [167]:
metrics.recall_score(y_test_5, y_pred_mul, average='micro')

0.469593237810075

# logistic for like and dislike classification

In [56]:
logreg = LogisticRegression()

In [57]:
logreg.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [58]:
import pickle
filename = 'C:/Users/manoj/Desktop/deep_learning/final_project/book/logistic_binary.h5'
pickle.dump(logreg_mul, open(filename, 'wb'))

In [36]:
y_test = test_data.apply(lambda x:1 if x['rating']>3 else 0, axis=1)

In [37]:
X_test = test_data.drop(['user_id', 'book_id', 'rating'], axis=1)

In [38]:
X_test.head()

avg_rating       0_x       1_x       2_x       3_x       4_x       5_x  \
0    4.193548  0.182297  0.030095  0.013480  0.015648  0.008251  0.024029   
1    4.418605  0.202271  0.000826  0.013064  0.000000  0.006972  0.042788   
2    4.673077  0.199032  0.000000  0.012913  0.022732  0.017535  0.062679   
3    3.500000  0.176218  0.008017  0.035940  0.016299  0.003869  0.043797   
4    3.864198  0.197760  0.054557  0.007288  0.025506  0.007168  0.056290   

        6_x       7_x       8_x    ...         15_y      16_y      17_y  \
0  0.010569  0.065474  0.017790    ...     0.000000  0.002823  0.000000   
1  0.009791  0.006833  0.036326    ...     0.000000  0.000000  0.000000   
2  0.028635  0.017032  0.020711    ...     0.000000  0.007510  0.000000   
3  0.001564  0.040279  0.026325    ...     0.000000  0.000000  0.000000   
4  0.002485  0.016126  0.020709    ...     0.000244  0.010929  0.000064   

       18_y      19_y      20_y      21_y      22_y      23_y      24_y  
0  0.000000  0.001451  0.010203  0.006101  0.001625  0.000187  0.000000  
1  0.000000  0.000000  0.000000  0.000000  0.729505  0.000000  0.000000  
2  0.000000  0.000000  0.018864  0.000000  0.000000  0.008654  0.007507  
3  0.000000  0.004526  0.000304  0.000000  0.001580  0.000362  0.000279  
4  0.000748  0.000000  0.000508  0.000511  0.004363  0.000302  0.018874  

[5 rows x 62 columns]

In [30]:
y_pred = logreg.predict(X_test)

In [31]:
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(X_test, y_test)))

Accuracy of logistic regression classifier on test set: 0.73


In [68]:
probability = logreg.predict_proba(X_test)

In [90]:
probability

array([[0.23753886, 0.76246114],
       [0.18549318, 0.81450682],
       [0.10486548, 0.89513452],
       ...,
       [0.13652356, 0.86347644],
       [0.20529486, 0.79470514],
       [0.60862731, 0.39137269]])

In [84]:
class_1_prob=probability[:,0]

In [85]:
class_2_prob= probability[:,1]

In [88]:
from numpy import maximum

result = maximum(class_1_prob,class_2_prob)

In [89]:
result

array([0.76246114, 0.81450682, 0.89513452, ..., 0.86347644, 0.79470514,
       0.60862731])

In [81]:
logreg.score(X_test, y_test)

0.7330677513063423

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [38]:
evaluation_data = test_data[['user_id', 'book_id', 'rating']].copy()
evaluation_data['prediction']=y_pred

In [40]:
evaluation_data['binary_rating']=y_test

In [91]:
evaluation_data['pred_proba']= result

In [92]:
evaluation_data.head()

user_id  book_id  rating  prediction  binary_rating  pred_proba
0   18218      920       3           1              0    0.762461
1   34091      967       4           1              1    0.814507
2   41266       71       5           1              1    0.895135
3   47336      760       5           1              1    0.630520
4   20893      453       3           1              0    0.625717

In [45]:
print(cfm)

[[ 204268  352124]
 [ 126430 1109970]]


In [46]:
print(p, r)

0.7591645954364084 0.8977434487220964


In [93]:
mAP, n = top_10_binary_results(evaluation_data)

0 users evaluated
500 users evaluated
1000 users evaluated


C:\Users\manoj\Anaconda3\lib\site-packages\sklearn\metrics\ranking.py:444: RuntimeWarning: invalid value encountered in true_divide
  recall = tps / tps[-1]


1500 users evaluated
2000 users evaluated
2500 users evaluated
3000 users evaluated
3500 users evaluated
4000 users evaluated
4500 users evaluated
5000 users evaluated
5500 users evaluated
6000 users evaluated
6500 users evaluated
7000 users evaluated
7500 users evaluated
8000 users evaluated
8500 users evaluated
9000 users evaluated
9500 users evaluated
10000 users evaluated
10500 users evaluated
11000 users evaluated
11500 users evaluated
12000 users evaluated
12500 users evaluated
13000 users evaluated
13500 users evaluated
14000 users evaluated
14500 users evaluated
15000 users evaluated
15500 users evaluated
16000 users evaluated
16500 users evaluated
17000 users evaluated
17500 users evaluated
18000 users evaluated
18500 users evaluated
19000 users evaluated
19500 users evaluated
20000 users evaluated
20500 users evaluated
21000 users evaluated
21500 users evaluated
22000 users evaluated
22500 users evaluated
23000 users evaluated
23500 users evaluated
24000 users evaluated
24500

In [94]:
print(mAP, n)

0.6467533006913909 0


In [50]:
from sklearn.metrics import average_precision_score, confusion_matrix, recall_score, precision_score
import numpy as np


def replay_binary_results(evaluation_data):
    """
    To be used for predictions for the books rated in the test set.
    Parameter
    ---------
    evaluation_data: pd.DataFrame
        Expected columns: prediction, binary_rating
        prediction is the predicted class (0/1)
        binary_rating is the binarized ratings where [1, 2, 3] -> 0, [4, 5] -> 1
    Returns
    -------
    Confusion matrix, precision and recall
    """
    cfm = confusion_matrix(evaluation_data['binary_rating'], evaluation_data['prediction'])
    precision = precision_score(evaluation_data['binary_rating'], evaluation_data['prediction'])
    recall = recall_score(evaluation_data['binary_rating'], evaluation_data['prediction'])
    return cfm, precision, recall


def replay_5star_results(evaluation_data):
    """
    To be used for predictions for the books rated in the test set.
    Parameter
    ---------
    evaluation_data: pd.DataFrame
        Expected columns: prediction, rating
        prediction is the predicted class (1-5)
        rating is original rating
    Returns
    -------
    Confusion matrix, precision and recall
    """
    cfm = confusion_matrix(evaluation_data['rating'], evaluation_data['prediction'])
    precision = precision_score(evaluation_data['rating'], evaluation_data['prediction'], average='weighted')
    recall = recall_score(evaluation_data['rating'], evaluation_data['prediction'], average='weighted')
    return cfm, precision, recall


def top_n_binary_results(evaluation_data, n=10):
    """
    Evaluates the top 10 recommendations for each user.
    To be used for predictions for all books not in the user's training data.
    Parameter
    ---------
    evaluation_data: pd.DataFrame
        Expected columns: user_id, book_id, pred_proba, prediction, binary_rating
        pred_proba is the probability of being a 1
        prediction is the predicted class (0/1)
        binary_rating is the binarized ratings where [1, 2, 3] -> 0, [4, 5] -> 1
    Returns
    -------
    The mAP and the number of users who had no historic rating data for any of their predicted top 10
    """
    users = list(set(evaluation_data['user_id'].tolist()))

    aps = []
    not_scored = []
    counter = 0
    for u in users:
        results = evaluation_data[evaluation_data['user_id'] == u]
        books = results['book_id'].tolist()
        probs = np.asarray(results['pred_proba'])
        top_10 = np.argsort(probs)[:n]
        top_books = []
        top_ratings = []
        for i in top_10:
            rating = results[results['book_id'] == books[i]]['binary_rating'].values
            if rating >= 0:
                top_books.append(results[results['book_id'] == books[i]]['prediction'].values)
                top_ratings.append(results[results['book_id'] == books[i]]['binary_rating'].values)
        if len(top_ratings) > 0:
            ap = average_precision_score(np.array(top_ratings), np.array(top_books))
            if np.isnan(ap):
                aps.append(0)
            else:
                aps.append(ap)
        else:
            not_scored.append(u)

        if counter % 500 == 0:
            print(str(counter), 'users evaluated')
        counter +=1

    mAP = np.asarray(aps).mean()
    return mAP, len(not_scored)



def top_n_5star_results(evaluation_data, n=10):
    """
    Evaluates the top 10 recommendations for each user.
    To be used for predictions for all books not in the user's training data.
    Parameter
    ---------
    evaluation_data: pd.DataFrame
        Expected columns: user_id, book_id, pred_proba, prediction, binary_rating
        pred_proba is the probability of being a 5
        prediction is the predicted class (1-5)
        rating is the original rating
    Returns
    -------
    The mAP and the number of users who had no historic rating data for any of their predicted top 10.
    Also calculates mAP for whether or not the user enjoyed the book (4 or 5).
    """
    users = list(set(evaluation_data['user_id'].tolist()))

    aps = []
    binary_aps = []
    not_scored = []
    counter = 0
    for u in users:
        results = evaluation_data[evaluation_data['user_id'] == u]
        books = results['book_id'].tolist()
        probs = np.asarray(results['pred_proba'])
        top_10 = np.argsort(probs)[:n]
        true = {1: [], 2: [], 3: [], 4: [], 5: []}
        pred = {1: [], 2: [], 3: [], 4: [], 5: []}
        top_binary_books = []
        top_binary_ratings = []
        matches = 0
        for i in top_10:
            rating = results[results['book_id'] == books[i]]['rating'].values
            
            if rating > 0:
                matches += 1
                p = int(results[results['book_id'] == books[i]]['prediction'].values)
                r = int(results[results['book_id'] == books[i]]['rating'].values)
                if p == r:
                    true[r].append(1)
                    pred[r].append(1)
                    for i in range(1, 6):
                        if i != r:
                            true[i].append(0)
                            pred[i].append(0)
                else:
                    true[r].append(1)
                    pred[r].append(0)
                    true[p].append(0)
                    pred[p].append(1)
                    for i in range(1, 6):
                        if i != r and i != p:
                            true[i].append(0)
                            pred[i].append(0)
                
                pb = 1 if p > 3 else 0
                rb = 1 if r > 3 else 0

                top_binary_books.append(pb)
                top_binary_ratings.append(rb)
                
        if matches > 0:
            ap_1 = average_precision_score(true[1], pred[1]) if len(true[1]) > 0 else 0
            ap_2 = average_precision_score(true[2], pred[2]) if len(true[2]) > 0 else 0
            ap_3 = average_precision_score(true[3], pred[3]) if len(true[3]) > 0 else 0
            ap_4 = average_precision_score(true[4], pred[4]) if len(true[4]) > 0 else 0
            ap_5 = average_precision_score(true[5], pred[5]) if len(true[5]) > 0 else 0
            weighted_ap = len(true[1])/matches * ap_1 + len(true[2])/matches * ap_2 + len(true[3])/matches * ap_3 + len(true[4])/matches * ap_4 + len(true[5])/matches * ap_5
            if np.isnan(weighted_ap):
                weighted_ap = 0
            aps.append(weighted_ap)
            
            b_ap = average_precision_score(top_binary_ratings, top_binary_books)
            if np.isnan(b_ap):
                b_ap = 0
            binary_aps.append(b_ap)
            
        else:
            not_scored.append(u)
        if counter % 500 == 0:
            print(str(counter), 'users evaluated')
        counter += 1

    mAP = np.asarray(aps).mean()
    binary_mAP = np.asarray(binary_aps).mean()
    return aps, mAP, binary_mAP, binary_aps, len(not_scored)

# Cold Start

In [60]:
cold_start_user = pd.DataFrame(np.zeros((10000, 26)))

In [61]:
cold_start_data = cold_start_user.merge(book_features.drop('book_id', axis=1), left_index=True, right_index=True)

In [62]:
cold_start_data.head()

0    1    2    3    4    5    6    7    8    9    ...           15  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.000000   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.000000   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.000000   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.002680   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.011253   

         16        17        18       19   20   21        22        23  \
0  0.000000  0.000000  0.000668  0.00000  0.0  0.0  0.000000  0.009848   
1  0.000000  0.000000  0.000000  0.00000  0.0  0.0  0.000000  0.000000   
2  0.000000  0.026678  0.000000  0.00000  0.0  0.0  0.000000  0.007945   
3  0.000000  0.000000  0.009918  0.04148  0.0  0.0  0.000847  0.021077   
4  0.000036  0.000000  0.000000  0.00000  0.0  0.0  0.000000  0.000000   

         24  
0  0.000000  
1  0.000000  
2  0.000000  
3  0.031681  
4  0.000000  

[5 rows x 62 columns]

In [67]:
binary_model = pickle.load(open('C:/Users/manoj/Desktop/deep_learning/final_project/book/logistic_binary.h5', 'rb'))

In [69]:
predictions = binary_model.predict(cold_start_data)

In [70]:
predictions

array([1, 3, 1, ..., 3, 3, 3], dtype=int64)

In [71]:
cold_start_users = pd.read_csv('C:/Users/manoj/Desktop/deep_learning/final_project/book/cold_start_ratings_set.csv')

In [72]:
cold_start_users.head()

user_id  book_id  rating
0        1      258       5
1        2     4081       4
2        2      260       5
3        2     9296       5
4        2     2318       3

In [75]:
users = list(set(cold_start_users['user_id'].tolist()))
users

[1, 2, 3, 4, 5]

In [85]:
pred_dfs = []
users = list(set(cold_start_users['user_id'].tolist()))

for index, user in enumerate(users):
    
    all_books = cold_start_users[cold_start_users['user_id'] == user]['book_id'].tolist()
    idx = [b - 1 for b in all_books]
    filter_books = cold_start_users[cold_start_users['user_id'] == user]
    test_book_ratings = filter_books[filter_books['book_id'].isin(all_books)]['rating'].tolist()

    #print(len(test_book_ratings))

    raw_predictions = result[idx].reshape(1, -1)[0]
    
    #print(raw_predictions.shape)
    df = pd.DataFrame({'book_id': all_books, 
                       'rating': test_book_ratings,
                       'pred_proba': raw_predictions})
    df['user_id'] = user
    pred_dfs.append(df)
    
evaluate_df = pd.concat(pred_dfs, ignore_index=True)

evaluate_df.head()

book_id  pred_proba  rating  user_id
0      258    0.998807       5        1
1      268    0.999461       3        1
2     5556    0.999710       3        1
3     3638    0.999459       3        1
4     1796    0.999493       5        1

In [76]:
probability = logreg.predict_proba(cold_start_data)

In [78]:
from numpy import maximum
class_1_prob=probability[:,0]
class_2_prob=probability[:,1]
result = maximum(class_1_prob,class_2_prob)

In [86]:
evaluate_df['binary_rating'] = evaluate_df.apply(lambda x: 1 if x['rating'] > 3 else 0, axis=1)

min_p = evaluate_df['pred_proba'].min()
max_p = evaluate_df['pred_proba'].max()

def scale_prediction_binary(x, min_p, max_p):
    raw = (x - min_p) / (max_p - min_p)
    return np.rint(raw)

evaluate_df['prediction'] = evaluate_df.apply(lambda x: scale_prediction_binary(x['pred_proba'], min_p, max_p), axis=1)
evaluate_df['prediction'].value_counts()

1.0    491
0.0     16
Name: prediction, dtype: int64

In [88]:
cfm, p, r = replay_binary_results(evaluate_df)
cfm

array([[  0, 220],
       [ 16, 271]], dtype=int64)

In [89]:
print(p, r)

0.5519348268839104 0.9442508710801394


In [90]:
mAP, skipped =top_n_binary_results(evaluate_df, 10)

0 users evaluated


In [91]:
mAP

0.7492857142857143

# multiclass cold start

In [92]:
Multiclass_model = pickle.load(open('C:/Users/manoj/Desktop/deep_learning/final_project/book/logistic.h5', 'rb'))

In [93]:
star5_predictions = Multiclass_model.predict(cold_start_data)

In [98]:
probability = Multiclass_model.predict_proba(cold_start_data)

In [111]:
star5_predictions.shape

(10000,)

In [118]:
pred_dfs = []

for index, user in enumerate(users):
    
    all_books = cold_start_users[cold_start_users['user_id'] == user]['book_id'].tolist()
    idx = [b - 1 for b in all_books]
    filter_books = cold_start_users[cold_start_users['user_id'] == user]
    test_book_ratings = filter_books[filter_books['book_id'].isin(all_books)]['rating'].tolist()

    #print(len(test_book_ratings))

    pred = star5_predictions[idx]

    pred_proba = probability[idx,4]

    
    #print(raw_predictions.shape)
    df = pd.DataFrame({'book_id': all_books, 
                       'rating': test_book_ratings,
                       'pred_proba': pred_proba, 
                       'prediction': pred})
    df['user_id'] = user
    pred_dfs.append(df)
    
evaluate_df = pd.concat(pred_dfs, ignore_index=True)

evaluate_df.head()

book_id  pred_proba  prediction  rating  user_id
0      258    0.000021           3       5        1
1      268    0.000008           3       3        1
2     5556    0.000004           3       3        1
3     3638    0.000009           3       3        1
4     1796    0.000009           3       5        1

In [120]:
cfm, p, r = replay_5star_results(evaluate_df)
cfm

C:\Users\manoj\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


array([[  0,   2,  54,   0,   0],
       [  1,   2,  39,   0,   0],
       [  0,   0, 122,   0,   0],
       [  2,   1, 164,   0,   0],
       [  2,   1, 117,   0,   0]], dtype=int64)

In [121]:
print(p, r)

0.0868009162053827 0.2445759368836292


In [122]:
APs, mAP, binary_mAP, bmAPs, skipped = top_n_5star_results(evaluate_df, 10)

0 users evaluated


C:\Users\manoj\Anaconda3\lib\site-packages\sklearn\metrics\ranking.py:444: RuntimeWarning: invalid value encountered in true_divide
  recall = tps / tps[-1]


In [123]:
print(mAP, binary_mAP)

0.255 0.38
